apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo-flask-mvc
  name: todo-flask-mvc-config
  labels:
    app: todo-flask-mvc
data:
  APP_NAME: "todo-flask-mvc"
  FOO: "bar"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: todo-flask-mvc
  name: todo-flask-mvc-secrets 
data:
  FOO: "YmFy"


