name: CICD
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build --progress=plain --tag binlecode/${{ github.repository }}:${{ github.sha }} .
      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push binlecode/${{ github.repository }}:${{ github.sha }}
