name: CICD
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          # docker build --progress=plain --tag ${{ github.repository }}:${{ github.sha }} .
          docker build --progress=plain --tag ikalidocker/example-todo-flask-mvc:${{ github.sha }} .
      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          # docker push ${{ github.repository }}:${{ github.sha }}
          docker push ikalidocker/example-todo-flask-mvc:${{ github.sha }}
